### ISSUE TITLE
Doesn't appear to work anymore

### ISSUE THREAD

**Issue by dpeart** [LelandP/heatmaster_homeassistant#1]
I just fired up my boiler and it doesn't appear this is working anymore.

The Heatmaster stuff didn't change, but it makes we wonder if something broke because of changes in HA?

thanks
david

**Comment by dpeart** [comment]
Maybe I spoke too soon.  I do see everything but status working now.

**Comment by dpeart** [comment]
I am getting errors.
The status no longer updates.  I'm also getting this error, something probably change in HA over the summer.

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:732
First occurred: October 31, 2023 at 10:24:21 PM (1103 occurrences)
Last logged: 3:44:09 PM

Update for sensor.heatmaster_hassio_water_temperature fails
Update for sensor.heatmaster_hassio_o2 fails
Update for sensor.heatmaster_hassio_top_damper fails
Update for sensor.heatmaster_hassio_bottom_damper fails
Update for sensor.heatmaster_hassio_furnace_status fails
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 732, in async_update_ha_state
    await self.async_device_update()
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 993, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heatmaster_hassio/sensor.py", line 97, in update
    self._value = self.hm.data[self._value_key]
                  ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by LelandP** [comment]
My boiler isn't running yet, waiting for it to get a bit cooler. One I start it up I'll fix this issue.

**Comment by dpeart** [comment]
No rush.  thanks

**Comment by LelandP** [comment]
@dpeart I pushed an update today, it should be working now.

**Comment by dpeart** [comment]
I just updated and it is working.

thanks
